### PR TITLE
Added JSON Schema for configuration in appsettings.json 

### PR DESCRIPTION
**Pull request by 304NotModified**
See https://github.com/NLog/NLog.Extensions.Logging/issues/295

Examples are validated with validate-examples.ps1 (so now only happy path tests). validate-examples will be run on Azure Devops

image

image

Todo

- [x] fix base Schema appsettings
- [x] CI
- [x] NLog under "Logging" (Logging:NLog)
- [ ] Check defaults of Logging:NLog

URL will be: https://nlog-project.org/schemas/appsettings.schema.json

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot please check,

I've made some changes since https://github.com/NLog/NLog.Extensions.Logging/pull/425 (see new commits)

- The enum is now not mandatory with the use of AnyOf. (but we still get auto completion!)
- I've added the provider options and all other options which aren't NLog's

**Comment by 304NotModified** [comment]
This could be tested in VS with this URL: https://raw.githubusercontent.com/NLog/NLog.github.io/9054838bfcc20f9b41603b74558ecdc72b2fd869/schemas/appsettings.schema.json

**Comment by snakefoot** [comment]
Think it looks great. Maybe have to target-file-examples. logfile and logfile-json.

Curious if one can include the most common target-symbol-names for the target-type-value.

**Comment by 304NotModified** [comment]
I think we could include the most used targets with an anyOf. 
But that's for next time :)

**Comment by 304NotModified** [comment]
Merge for now. Examples could be added later. (or other enhancements)

**Comment by ThomasArdal** [comment]
I think that a JSON schema for NLog is awesome. But as I see it, you extended the one I made with the Kestrel stuff inside, right? Are you sure you want to do that? Doing that file was just my quick attempt to make something better than the one on Schemastore. I don't think that I got everything added and right inside the `Logging` section. Maybe the NLog file should have been based on the "official" one on Schemastore instead?

**Comment by 304NotModified** [comment]
@ThomasArdal the more the better I think ;)

**Comment by ThomasArdal** [comment]
I would love to see much broader schema support. From Microsoft as well. IMO teams within Microsoft should extend the official file on Schemastore with their part of config options. Just not so sure of the stuff I've put in there. But fine for now. Let's see if anyone within Microsoft decides to move on this 👍

**Comment by snakefoot** [comment]
Should one continue to update this schema:

https://github.com/NLog/NLog.github.io/blob/master/schemas/appsettings.schema.json

When updating the NLog-section of this schema:

https://github.com/snakefoot/schemastore/blob/master/src/schemas/json/appsettings.json

?

**Comment by ThomasArdal** [comment]
That is totally up to you, of course. If it were me, I would discontinue the `appsettings.schema.json` file now that NLog config has been moved to the one on schemastore. I didn't remove it or change it when moving since someone can still have the old path configured in VS. Maybe it can be marked as obsolete somehow?

**Pull request merged**
