### PR TITLE
WIP NLog.Extensions.Logging 1.5 post

### PR DESCRIPTION
**Pull request by 304NotModified**
see https://github.com/NLog/NLog.Extensions.Logging/pull/263

### CODE REVIEW

**Comment by snakefoot** [comment]
Example code needs to be updated, as it is now called `NLogLoggingConfiguration` (And not `ExtensionLoggingConfiguration`)

**Comment by snakefoot** [comment]
Maybe also include this in the news post:

https://github.com/NLog/NLog.Extensions.Logging/pull/260

See also wiki page example:

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-cloud-logging-with-Azure-function-or-AWS-lambda#writing-to-microsoft-extension-ilogger-in-azure

**Comment by 304NotModified** [comment]
Good idea!

**Comment by snakefoot** [comment]
@304NotModified Maybe needs the finishing touch? Or waiting for https://github.com/NLog/NLog.Extensions.Logging/issues/290 ?

**Comment by 304NotModified** [comment]
This needs indeed some love. I only created this PR to preserve your text  👼

**Comment by 304NotModified** [comment]
@snakefoot What should be do with this PR

**Comment by snakefoot** [comment]
Think it has been replaced with this wiki-page: 

https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json

**Pull request closed without merging**
