### PR TITLE
Added NLog 4.7 news post

### PR DESCRIPTION
**Pull request by snakefoot**
First draft of NLog 4.7 news post

Could consider adding a link to https://github.com/NLog/NLog/wiki/Configure-from-code#logfactory-initial-setup (Place where users can edit easily)

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Amazing how one NLog 4.7 has been released exactly one year after NLog 4.6

**Comment by 304NotModified** [comment]
Thanks!

(Maybe we could take another title otherwise it's always the same :) )

**Comment by snakefoot** [comment]
My mind is not that creative. But please rename away.

**Comment by 304NotModified** [comment]
Thanks! I'm happy with the content! Added it to the site :)

**Comment by snakefoot** [comment]
Happy you like it. Have made a minor addition here: #142

**Pull request merged**
