### PR TITLE
Make it more explicit that it is Symbol type-name

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot not sure if this is a good change.

I have difficulties to explain layout renderers as term. And `Symbol type-name` is even more difficult.

**Comment by 304NotModified** [comment]
non in code: https://github.com/NLog/NLog/search?q=Symbol+type-name&type=code

**Comment by snakefoot** [comment]
It is target type=symbol-name. It also symbol-name not found.

And it is the symbol-name that has support alias and dash-handling.

Maybe "Type Symbol-Name" instead of "Symbol Type-Name"?



Sent from my Galaxy



-------- Original message --------
From: Julian Verdurmen ***@***.***>
Date: 23/05/2022 22:57 (GMT+01:00)
To: "NLog/NLog.github.io" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Mention ***@***.***>
Subject: Re: [NLog/NLog.github.io] Make it more explicit that it is Symbol type-name (PR #200)


non in code: https://github.com/NLog/NLog/search?q=Symbol+type-name&type=code

**Comment by 304NotModified** [comment]
I don't know what the symbol is in this case. It's new term

**Comment by 304NotModified** [comment]
I don't think there is an umbrella term for targets, layouts, layout renderers and conditions. Maybe layoutable?

**Comment by 304NotModified** [comment]
Symbol in the context of .NET ;)

https://docs.microsoft.com/en-us/dotnet/core/diagnostics/symbols

**Comment by snakefoot** [comment]
The type-name in .NET world is the full class-type. Ex. `LocalIpAddressLayoutRenderer` and its symbol-name / call-name / type-alias is `local-ip`

**Comment by snakefoot** [comment]
Created #202

**Pull request merged**
