### PR TITLE
Add .NET Standard 1.6 platform in search filter.

### PR DESCRIPTION
**Pull request by linmasaki**
Sorry, I can't find ".NET Standard 1.6" option in search select items, so I added it in the js file. If there any reason you don't want show it in select list, please tell me and ignore this commit. Thank you!

### CODE REVIEW

**Comment by 304NotModified** [comment]
it was not needed before :)

So this is 👍

**Comment by 304NotModified** [comment]
it needed to add it now everywhere, that's done in 68771b207bdf77e330f64beba732a143edde56a2

**Comment by 304NotModified** [comment]
PS: I reverted this, as this isn't needed anymore. There is no package that is special for 1.6 anymore

**Comment by linmasaki** [comment]
OK, Thank you for your hard work. I think maybe most of the situation 1.5 almost equals 1.6.

**Pull request merged**
