### PR TITLE
fixed error on loading targets Documentation Page

### PR DESCRIPTION
**Pull request by cboland-task**
trailing , removed.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! Too bad the trialing comma is accepted by the tests.

**Comment by cboland-task** [comment]
Thanks, sorry for the mess.
By the way, can I build the documentation site by myself? Just in case... 
I looked for a package.json (or similar) but was too blind to find anything.

**Comment by 304NotModified** [comment]
The most of the site is in jekyll, https://jekyllrb.com/

But the config page is build with Vuejs.

**Comment by 304NotModified** [comment]
The build should be fixed so the trailing comma won't be accepted anymore :)

**Pull request merged**
