### PR TITLE
Updated NLog Homepage with extra features items

### PR DESCRIPTION
**Pull request by snakefoot**
NLog doesn't have a ASP.NET Core Target, but do have support for Microsoft Extension Logging and appsettings.json.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Looks good, but now sure how it renders

**Comment by snakefoot** [comment]
Believe "Features"-list should render like "Targets"-list

**Comment by 304NotModified** [comment]
Could you please try this on your fork? E.g. like https://304notmodified.github.io/

**Comment by 304NotModified** [comment]
(Or pr to https://304notmodified.github.io/ also fine)

**Comment by snakefoot** [comment]
Created: https://github.com/304NotModified/304NotModified.github.io/pull/2

**Comment by snakefoot** [comment]
HTML Layout looks good, but maybe there should a link for the "Microsoft Extensible Logging"-feature

**Comment by 304NotModified** [comment]
> 304NotModified#2

Yes please, also noticed that (and reported at: https://github.com/304NotModified/304NotModified.github.io/pull/2)

**Comment by snakefoot** [comment]
Fixed

**Comment by snakefoot** [comment]
Think it looks good now.

**Comment by 304NotModified** [comment]
Thanks again!

**Pull request merged**
