### PR TITLE
NLog 5.0 Release Post

### PR DESCRIPTION
**Pull request by snakefoot**
Official release-post for NLog 5.0 RTM

Preview: https://github.com/snakefoot/NLog.github.io/blob/master/_posts/2022-05-14-nlog-5-0-finally-ready.md

### CODE REVIEW

**Comment by snakefoot** [comment]
Still interested in getting #183 merged, so I can prepare pull-request with the new NLog 5.0 packages.

**Comment by 304NotModified** [comment]
I'm sorry, but I am very busy these weeks

**Comment by snakefoot** [comment]
Just have to wait then :)

**Comment by snakefoot** [comment]
@304NotModified How does the weeks look these days? Any chance for having the platform-cleanup #183 merged?

**Comment by 304NotModified** [comment]
Will merged after this is green: https://ci.appveyor.com/project/nlog/nlog

**Pull request merged**
