### PR TITLE
Update "appsettings" layout renderer description.

### PR DESCRIPTION
**Pull request by linmasaki**
Also add platform properties.

### CODE REVIEW

**Comment by 304NotModified** [comment]
thanks!

**Comment by 304NotModified** [comment]
I'm sorry, but now ${configsetting} has landing to NLog, this renderer is a duplicate. I don't think it's a good idea to keep duplicate renderers in the list.

**Comment by 304NotModified** [comment]
PS: added your name to the changelog: https://github.com/NLog/NLog.Extensions.Logging/blob/master/CHANGELOG.MD

**Comment by linmasaki** [comment]
No problem, I am very delighted to see that NLog supports this renderer. Thanks!

**Pull request merged**
