### PR TITLE
Update targets.json

### PR DESCRIPTION
**Pull request by cboland-task**
Added NLog Target description for MS Teams Target

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thx!

**Comment by nerijusdu** [comment]
I believe this PR introduced an issue in https://nlog-project.org/config/?tab=targets, where targets never load. Probably because of the dangling comma in line 951.
image

**Comment by cboland-task** [comment]
fixed the trailing , 
see 
https://github.com/NLog/NLog.github.io/pull/160

**Comment by 304NotModified** [comment]
Thanks for the fix. I don't know why the trailing comma is accepted by jsonlint. It's certainly not valid json.

**Comment by 304NotModified** [comment]
For some reason azure devops wasn't triggered.  I made to check required so this should not happen in the future :)

**Pull request merged**
