### PR TITLE
Added schema for the elmah.io target for NLog

### PR DESCRIPTION
**Pull request by ThomasArdal**
My first attempt to create a schema for the elmah.io target for NLog.

### CODE REVIEW

**Comment by 304NotModified** [comment]
isn't "NLog.Targets.Elmah.io.xsd" a better name?

**Comment by ThomasArdal** [comment]
You are probably right. The target is named Elmah.Io.NLog actually. Maybe that was a mistake :smile: I'll change the name for the xsd. Thx!

**Comment by 304NotModified** [comment]
👍

**Comment by ThomasArdal** [comment]
@304NotModified I'm wondering why this config doesn't work with the new schema:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:elmahio="http://www.nlog-project.org/schemas/NLog.Targets.Elmah.Io.xsd"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="C:\temp\internal-nlog.txt">

  <extensions>
    <add assembly="Elmah.Io.NLog" />
  </extensions>

  <targets>
    <target name="elmahio" xsi:type="elmahio:elmah.io" apiKey="API_KEY" logId="LOG_ID" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="elmahio" />
  </rules>
</nlog>
```

Any ideas?

**Comment by 304NotModified** [comment]
maybe we should test this one? https://github.com/graffen/NLog.Targets.Syslog/blob/master/src/TestApp/NLog.config

**Comment by ThomasArdal** [comment]
I'll do that later today.

**Comment by ThomasArdal** [comment]
Very weird. Intellisense works fine in TestApp, but if I add the exact same config in another project, it doesn't work. I've written a mail to graffen.

**Comment by 304NotModified** [comment]
Which editor do you use? Is the xsd file downloaded?

**Comment by ThomasArdal** [comment]
I'm using VS2017. The `NLog.Targets.Syslog.xsd` file is only in my clone of `NLog.github.io` and in the `src\NLog.Targets" folder in the clone of `NLog.Targets.Syslog`.

**Comment by 304NotModified** [comment]
And you have enabled auto download of xsd files? (Disavows by default, search in option on "xsd")

On mobile now, can't test now

**Comment by ThomasArdal** [comment]
Cannot seem to find that setting. Anyway, it works in the TestApp inside VS2017, why it should work in the other project as well.

**Comment by ThomasArdal** [comment]
But it sure look like my project is missing that schema. If I click XML | Schemas in `TestApp`, the `NLog.Targets.SysLog.xsd` file is there. And in my project it isn't. If I add it manually to my project, Intellisense works just fine.

**Comment by ThomasArdal** [comment]
And elmah.io intellisense works as well, as long as I manually add the `NLog.Targets.Elmah.Io.xsd` file to XML | Schemas.

**Comment by 304NotModified** [comment]
I meant this one:

image


But it looks it doesn't work in vs for me also :(

image

**Comment by 304NotModified** [comment]
got it!

1xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd http://www.nlog-project.org/schemas/NLog.Targets.Syslog.xsd">`

image

**Comment by 304NotModified** [comment]
and two @ThomasArdal 

image

**Comment by ThomasArdal** [comment]
That's awesome! Will try to migrate my sample projects tomorrow (on a mobile too and watching The Path on HBO which kind of sucks :smile: ). Thanks man!

**Comment by 304NotModified** [comment]
👍 

Recently started "12 monkeys" (the tv serie) on Netflix - http://www.imdb.com/title/tt3148266/

Really like it (but I almost always like time traveling ;) )

**Comment by ThomasArdal** [comment]
Started on that but wasn't hooked. Love the movie, though. If you like movie turned TV show, you should check out Westworld (if you haven't already).

**Comment by ThomasArdal** [comment]
Worked like a charm. Thank you, mate.

**Pull request merged**
