### PR TITLE
Update NLog.Targets.Syslog schema to v4.0.0

### PR DESCRIPTION
**Pull request by luigiberrettini**

### CODE REVIEW

**Comment by 304NotModified** [comment]
maybe it would be nice to set a `<xsd:annotation>` with "Introduced in 
NLog.Targets.Syslog 4" ?

See https://msdn.microsoft.com/en-us/library/ms256102(v=vs.110).aspx

**Comment by luigiberrettini** [comment]
No problem in adding the annotation, but I am thinking about the way we publish schemas.

I already have a NuGet package with the schema aligned to the target version and would like to ask you what is the best solution in your opinion:
 - a schema file for each target updated to the latest version
   effort of changing every time the xsd annotation, file not used for its contents but only to have a URL to which XMLs can point to (an empty file would be the same?)
 - a folder for each target with schema files having a name that specify the version
   effort of changing file name, users should change URL in their XML every time, file can be used for its contents

Thanks!

**Comment by 304NotModified** [comment]
> a schema file for each target updated to the latest version

I think that's  easiest was for us and end-users isn't it?

**Comment by 304NotModified** [comment]
merge this one and annotations in a later phase?

**Comment by luigiberrettini** [comment]
Sorry for the delay, I agree with you on the approach

**Pull request merged**
